apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_deployment
  namespace: cneNamespace
  labels: 
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
        - name: nginx_config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx_config
        configMap:
          name: nginx_config