apiVersion: v1
kind: Service
metadata:
  name: nginx_loadbalancer
  namespace: cneNamespace
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer